# Global Weekly EDA

## Load Data

In [1]:
import pandas as pd
import duckdb
from pathlib import Path
import openpyxl
print("openpyxl is working") # for reading excel files

openpyxl is working

In [2]:
DATA_PATH = Path("../data/raw")

print(DATA_PATH)
print(DATA_PATH.exists())

df = pd.read_excel(DATA_PATH / "global_weekly.xlsx")

..\data\raw
True

c:\Users\adelo\de25\Netflix_Analytics_DE_UX\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

## Inspect DataFrame and Table

In [3]:
df.head()

,country_name,country_iso2,week,category,weekly_rank,show_title,season_title,cumulative_weeks_in_top_10
0,Argentina,AR,2026-03-15,Films,1,War Machine,NaN,2
1,Argentina,AR,2026-03-15,Films,2,Strangers in the Park,NaN,2
2,Argentina,AR,2026-03-15,Films,3,Joker: Folie à Deux,NaN,1
3,Argentina,AR,2026-03-15,Films,4,Trolls Band Together,NaN,2
4,Argentina,AR,2026-03-15,Films,5,Double Jeopardy,NaN,1

In [4]:
df.shape

(458260, 8)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458260 entries, 0 to 458259
Data columns (total 8 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   country_name                458260 non-null  object
 1   country_iso2                458260 non-null  object
 2   week                        458260 non-null  object
 3   category                    458260 non-null  object
 4   weekly_rank                 458260 non-null  int64
 5   show_title                  458260 non-null  object
 6   season_title                223904 non-null  object
 7   cumulative_weeks_in_top_10  458260 non-null  int64
dtypes: int64(2), object(6)
memory usage: 28.0+ MB

## Check for NULLS and duplicates

In [6]:
df.isnull().sum()

country_name                       0
country_iso2                       0
week                               0
category                           0
weekly_rank                        0
show_title                         0
season_title                  234356
cumulative_weeks_in_top_10         0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

## Analysis

In [8]:
df.describe()

         weekly_rank  cumulative_weeks_in_top_10
count  458260.000000               458260.000000
mean        5.500000                    3.442231
std         2.872284                    6.057246
min         1.000000                    1.000000
25%         3.000000                    1.000000
50%         5.500000                    2.000000
75%         8.000000                    3.000000
max        10.000000                  127.000000

In [9]:
df["category"].value_counts()

category
Films    229130
TV       229130
Name: count, dtype: int64

In [10]:
df["country_name"].nunique()

94

In [11]:
df["week"].min(), df["week"].max()

('2021-07-04', '2026-03-15')

In [12]:
df.sort_values("weekly_rank").head(10)

,country_name,country_iso2,week,category,weekly_rank,show_title,season_title,cumulative_weeks_in_top_10
274930,New Caledonia,NC,2022-01-23,TV,1,Archive 81,Archive 81: Season 1,1
274970,New Caledonia,NC,2022-01-09,TV,1,Stay Close,Stay Close: Limited Series,2
458220,Vietnam,VN,2021-07-11,Films,1,Fast & Furious Presents: Hobbs & Shaw,NaN,1
60,Argentina,AR,2026-02-22,Films,1,Firebreak,NaN,1
274990,New Caledonia,NC,2022-01-02,TV,1,The Witcher,The Witcher: Season 2,3
274900,New Caledonia,NC,2022-01-30,Films,1,The Royal Treatment,NaN,2
274950,New Caledonia,NC,2022-01-16,TV,1,Stay Close,Stay Close: Limited Series,3
397110,Sweden,SE,2023-07-09,TV,1,The Witcher,The Witcher: Season 3,2
91690,Dominican Republic,DO,2023-03-19,TV,1,The Glory,The Glory: Season 1,3
397130,Sweden,SE,2023-07-02,TV,1,The Witcher,The Witcher: Season 3,1