# <center>Own EDA<center> 
<br>
<br>
Ask Kokchun: <br>
- for the KPI: avg_view_minute and complete_watch_rate <br>
- for the dilema: row for specific country Vs columns for global data

to do:
- use .lower()

In [3]:
import duckdb
import pandas as pd

In [23]:
df = pd.read_csv("../data/processed/netflix.csv")
df.head(1)

,Unnamed: 0,country_name,country_iso2,week,country_category,country_weekly_rank,show_title,season_title,country_cumulative_weeks_in_top_10,global_category,global_weekly_rank,global_weekly_hours_viewed,runtime,global_weekly_views,global_cumulative_weeks_in_top_10
0,0,Argentina,AR,2026-03-15,Films,1,War Machine,NaN,2,Films (English),1.0,80600000.0,109.002,44400000.0,2.0

In [29]:
duckdb.sql("""---sql
SELECT 
    country_name,
    global_weekly_hours_viewed,
    runtime,
    global_weekly_views
FROM
    df
WHERE
    show_title == 'War Machine'
""").df()

    country_name  global_weekly_hours_viewed  runtime  global_weekly_views
0      Argentina                  80600000.0  109.002           44400000.0
1      Argentina                  71400000.0  109.002           39300000.0
2      Australia                  80600000.0  109.002           44400000.0
3      Australia                  71400000.0  109.002           39300000.0
4        Austria                  80600000.0  109.002           44400000.0
..           ...                         ...      ...                  ...
181      Uruguay                  71400000.0  109.002           39300000.0
182    Venezuela                  80600000.0  109.002           44400000.0
183    Venezuela                  71400000.0  109.002           39300000.0
184      Vietnam                  80600000.0  109.002           44400000.0
185      Vietnam                  71400000.0  109.002           39300000.0

[186 rows x 4 columns]

### Counting numbers of raws and columns

In [5]:
# Counting numbers of raws and columns
df.shape
print(f"File has raws, columns: {df.shape}")

File has raws, columns: (458338, 15)

### The columns

In [6]:
# Viewing the columns
df.columns

Index(['Unnamed: 0', 'country_name', 'country_iso2', 'week',
       'country_category', 'country_weekly_rank', 'show_title', 'season_title',
       'country_cumulative_weeks_in_top_10', 'global_category',
       'global_weekly_rank', 'global_weekly_hours_viewed', 'runtime',
       'global_weekly_views', 'global_cumulative_weeks_in_top_10'],
      dtype='object')

### How many years are covered in the dataset?

In [8]:
df['week'] = pd.to_datetime(df['week'])
year_counts = df['week'].dt.year.value_counts()
year_counts

week
2023    98580
2022    96900
2024    96798
2025    96720
2021    48880
2026    20460
Name: count, dtype: int64

In [9]:
number_of_years = len(year_counts)
print(f"There are {number_of_years} years in the dataset")

There are 6 years in the dataset

### Checking for duplicates

In [10]:
# Counting the duplicates
df.duplicated().sum()

np.int64(0)

## <center>Data cleaning<center>

In [11]:
df

,Unnamed: 0,country_name,country_iso2,week,country_category,country_weekly_rank,show_title,season_title,country_cumulative_weeks_in_top_10,global_category,global_weekly_rank,global_weekly_hours_viewed,runtime,global_weekly_views,global_cumulative_weeks_in_top_10
0,0,Argentina,AR,2026-03-15,Films,1,War Machine,NaN,2,Films (English),1.0,80600000.0,109.002,44400000.0,2.0
1,1,Argentina,AR,2026-03-15,Films,2,Strangers in the Park,NaN,2,Films (Non-English),10.0,1600000.0,115.998,800000.0,2.0
2,2,Argentina,AR,2026-03-15,Films,3,Joker: Folie à Deux,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Argentina,AR,2026-03-15,Films,4,Trolls Band Together,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Argentina,AR,2026-03-15,Films,5,Double Jeopardy,NaN,1,Films (English),5.0,6200000.0,106.002,3500000.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
458333,458333,Vietnam,VN,2021-07-04,TV,6,Reply 1988,Reply 1988: Season 1,1,NaN,NaN,NaN,NaN,NaN,NaN
458334,458334,Vietnam,VN,2021-07-04,TV,7,"Nevertheless,","Nevertheless,: Limited Series",1,NaN,NaN,NaN,NaN,NaN,NaN
458335,458335,Vietnam,VN,2021-07-04,TV,8,Too Hot to Handle,Too Hot to Handle: Season 2,1,TV (English),2.0,62150000.0,NaN,NaN,1.0
458336,458336,Vietnam,VN,2021-07-04,TV,9,Record of Ragnarok,Record of Ragnarok: Season 1,1,TV (Non-English),10.0,9140000.0,NaN,NaN,1.0
458337,458337,Vietnam,VN,2021-07-04,TV,10,Crash Landing on You,Crash Landing on You: Limited Series,1,NaN,NaN,NaN,NaN,NaN,NaN

### Cleaning country code

In [12]:
# Cleaning country_iso2
df = duckdb.sql("""---sql
SELECT *
    RENAME (country_iso2 AS country_code) 
FROM 
    df
""").df()
df

,Unnamed: 0,country_name,country_code,week,country_category,country_weekly_rank,show_title,season_title,country_cumulative_weeks_in_top_10,global_category,global_weekly_rank,global_weekly_hours_viewed,runtime,global_weekly_views,global_cumulative_weeks_in_top_10
0,0,Argentina,AR,2026-03-15,Films,1,War Machine,None,2,Films (English),1.0,80600000.0,109.002,44400000.0,2.0
1,1,Argentina,AR,2026-03-15,Films,2,Strangers in the Park,None,2,Films (Non-English),10.0,1600000.0,115.998,800000.0,2.0
2,2,Argentina,AR,2026-03-15,Films,3,Joker: Folie à Deux,None,1,None,NaN,NaN,NaN,NaN,NaN
3,3,Argentina,AR,2026-03-15,Films,4,Trolls Band Together,None,2,None,NaN,NaN,NaN,NaN,NaN
4,4,Argentina,AR,2026-03-15,Films,5,Double Jeopardy,None,1,Films (English),5.0,6200000.0,106.002,3500000.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
458333,458333,Vietnam,VN,2021-07-04,TV,6,Reply 1988,Reply 1988: Season 1,1,None,NaN,NaN,NaN,NaN,NaN
458334,458334,Vietnam,VN,2021-07-04,TV,7,"Nevertheless,","Nevertheless,: Limited Series",1,None,NaN,NaN,NaN,NaN,NaN
458335,458335,Vietnam,VN,2021-07-04,TV,8,Too Hot to Handle,Too Hot to Handle: Season 2,1,TV (English),2.0,62150000.0,NaN,NaN,1.0
458336,458336,Vietnam,VN,2021-07-04,TV,9,Record of Ragnarok,Record of Ragnarok: Season 1,1,TV (Non-English),10.0,9140000.0,NaN,NaN,1.0
458337,458337,Vietnam,VN,2021-07-04,TV,10,Crash Landing on You,Crash Landing on You: Limited Series,1,None,NaN,NaN,NaN,NaN,NaN

!!! dataset shows rows for each country but these rows include "global" columns for global values...check with Kokchun

### Cleaning runtime to round it

In [13]:
# NaN --> 0 | rounding | float --> integer
df['runtime'] = df['runtime'].fillna(0).round(0).astype(int)
df.head(2)

,Unnamed: 0,country_name,country_code,week,country_category,country_weekly_rank,show_title,season_title,country_cumulative_weeks_in_top_10,global_category,global_weekly_rank,global_weekly_hours_viewed,runtime,global_weekly_views,global_cumulative_weeks_in_top_10
0,0,Argentina,AR,2026-03-15,Films,1,War Machine,None,2,Films (English),1.0,80600000.0,109,44400000.0,2.0
1,1,Argentina,AR,2026-03-15,Films,2,Strangers in the Park,None,2,Films (Non-English),10.0,1600000.0,116,800000.0,2.0

### Creating Average view in min avg_view_min (KPI)

In [14]:
# Using global columns for metrics like in perf marketing with avg engag. time (possibel KPI?)
#  Creatting a new column + exchanging Nan --> 0 + convert float --> integer
df['avg_view_min'] = ((df['global_weekly_hours_viewed'] * 60) / df['global_weekly_views']).fillna(0).round(0).astype(int)
df.head(1)

,Unnamed: 0,country_name,country_code,week,country_category,country_weekly_rank,show_title,season_title,country_cumulative_weeks_in_top_10,global_category,global_weekly_rank,global_weekly_hours_viewed,runtime,global_weekly_views,global_cumulative_weeks_in_top_10,avg_view_min
0,0,Argentina,AR,2026-03-15,Films,1,War Machine,None,2,Films (English),1.0,80600000.0,109,44400000.0,2.0,109

### Creating a complete watch rate complete_watch_rate

In [15]:
# Complete watch ratio to see the film portion that people saw / maybe better than avg_view_min because films have diff length (KPI?)
df['complete_watch_rate'] = df['avg_view_min'] / df['runtime']
df.head(2)
# Note: complete_watch_rate peut etre > a 1 ou 100%, erreur ou ok? = Kokchun | explanation: user can do backwards to watch somehting else or cut at 1 ?

,Unnamed: 0,country_name,country_code,week,country_category,country_weekly_rank,show_title,season_title,country_cumulative_weeks_in_top_10,global_category,global_weekly_rank,global_weekly_hours_viewed,runtime,global_weekly_views,global_cumulative_weeks_in_top_10,avg_view_min,complete_watch_rate
0,0,Argentina,AR,2026-03-15,Films,1,War Machine,None,2,Films (English),1.0,80600000.0,109,44400000.0,2.0,109,1.000000
1,1,Argentina,AR,2026-03-15,Films,2,Strangers in the Park,None,2,Films (Non-English),10.0,1600000.0,116,800000.0,2.0,120,1.034483

In [16]:
# Test of the above, by asc order to check if works
#df_sorted = df.sort_values(by=['complete_watch_ratio', 'avg_view_min'], ascending=False
duckdb.sql("""---sql
    SELECT 
        show_title as film,
        runtime,
        avg_view_min,
        complete_watch_rate
    FROM
        df
    ORDER BY 
        complete_watch_rate
""").df()

                        film  runtime  avg_view_min  complete_watch_rate
0                        Raw      156           137             0.878205
1                        Raw      156           137             0.878205
2                        Raw      156           137             0.878205
3                        Raw      156           137             0.878205
4                        Raw      156           137             0.878205
...                      ...      ...           ...                  ...
458333  The Umbrella Academy        0             0                  NaN
458334      Who Killed Sara?        0             0                  NaN
458335                  BEEF        0             0                  NaN
458336      The Marked Heart        0             0                  NaN
458337            Tin & Tina        0             0                  NaN

[458338 rows x 4 columns]

In [17]:
# Excluding when avg_view_min is == 0 and runtime == 0 as impossible
duckdb.sql("""
    SELECT 
        show_title as film,
        runtime,
        avg_view_min,
        complete_watch_rate
    FROM
        df
    WHERE 
        avg_view_min > 0
        AND runtime > 0
    ORDER BY 
        complete_watch_rate ASC
""").df().head(20)
# repetition comes the series and diff seasons

                     film  runtime  avg_view_min  complete_watch_rate
0                     Raw      156           137             0.878205
1                     Raw      156           137             0.878205
2                     Raw      156           137             0.878205
3                     Raw      156           137             0.878205
4                     Raw      156           137             0.878205
5             Kaiju No. 8      237           223             0.940928
6             Kaiju No. 8      237           223             0.940928
7             Kaiju No. 8      237           223             0.940928
8             Kaiju No. 8      237           223             0.940928
9             Kaiju No. 8      237           223             0.940928
10            Kaiju No. 8      237           223             0.940928
11            Kaiju No. 8      237           223             0.940928
12            Kaiju No. 8      237           223             0.940928
13            Kaiju No. 8      237           223             0.940928
14  Kalki 2898 AD (Hindi)      176           167             0.948864
15  Kalki 2898 AD (Hindi)      176           167             0.948864
16  Kalki 2898 AD (Hindi)      176           167             0.948864
17  Kalki 2898 AD (Hindi)      176           167             0.948864
18  Kalki 2898 AD (Hindi)      176           167             0.948864
19  Kalki 2898 AD (Hindi)      176           167             0.948864

# <center>First EDA Attempt Spotted Issues<center>

### While doing the EDA, I noticed that we could not use the merged file. Below is what led me to the conclusion.

### Countries and rows

In [18]:
# Checking countries Vs rows 
df["country_name"].value_counts()

country_name
Argentina               4922
Bahamas                 4922
Chile                   4922
Colombia                4922
Brazil                  4922
                        ...
Sweden                  4920
United States           4920
United Arab Emirates    4920
Vietnam                 4920
Russia                   700
Name: count, Length: 94, dtype: int64

### Why the difference for Russia? Started later?

In [19]:
df[df["country_name"] == "Russia"].sort_values("week", ascending=True)

,Unnamed: 0,country_name,country_code,week,country_category,country_weekly_rank,show_title,season_title,country_cumulative_weeks_in_top_10,global_category,global_weekly_rank,global_weekly_hours_viewed,runtime,global_weekly_views,global_cumulative_weeks_in_top_10,avg_view_min,complete_watch_rate
345163,345163,Russia,RU,2021-07-04,TV,10,Lucifer,Lucifer: Season 5,1,TV (English),6.0,16890000.0,0,NaN,1.0,0,NaN
345144,345144,Russia,RU,2021-07-04,Films,1,Fatherhood,None,1,Films (English),1.0,25680000.0,0,NaN,1.0,0,NaN
345145,345145,Russia,RU,2021-07-04,Films,2,Wish Dragon,None,1,Films (English),3.0,15260000.0,0,NaN,1.0,0,NaN
345146,345146,Russia,RU,2021-07-04,Films,3,Fear Street Part 1: 1994,None,1,Films (English),2.0,16620000.0,0,NaN,1.0,0,NaN
345147,345147,Russia,RU,2021-07-04,Films,4,Good on Paper,None,1,Films (English),5.0,10580000.0,0,NaN,1.0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
344481,344481,Russia,RU,2022-02-27,TV,8,Ozark,Ozark: Season 1,6,None,NaN,NaN,0,NaN,NaN,0,NaN
344482,344482,Russia,RU,2022-02-27,TV,9,Squid Game,Squid Game: Season 1,19,None,NaN,NaN,0,NaN,NaN,0,NaN
344483,344483,Russia,RU,2022-02-27,TV,10,Money Heist,Money Heist: Part 5,16,None,NaN,NaN,0,NaN,NaN,0,NaN
344474,344474,Russia,RU,2022-02-27,TV,1,Inventing Anna,Inventing Anna: Limited Series,3,TV (English),1.0,130800000.0,0,NaN,3.0,0,NaN
344464,344464,Russia,RU,2022-02-27,Films,1,The Tinder Swindler,None,4,Films (English),2.0,17670000.0,0,NaN,4.0,0,NaN

In [20]:
# Russia: years account
russia_weeks = df[df["country_name"] == "Russia"]["week"].value_counts()
print(f"The registered weeks/years for Russia are: {russia_weeks}")

The registered weeks/years for Russia are: week
2022-02-27    20
2022-02-20    20
2022-02-13    20
2022-02-06    20
2022-01-30    20
2022-01-23    20
2022-01-16    20
2022-01-09    20
2022-01-02    20
2021-12-26    20
2021-12-19    20
2021-12-12    20
2021-12-05    20
2021-11-28    20
2021-11-21    20
2021-11-14    20
2021-11-07    20
2021-10-31    20
2021-10-24    20
2021-10-17    20
2021-10-10    20
2021-10-03    20
2021-09-26    20
2021-09-19    20
2021-09-12    20
2021-09-05    20
2021-08-29    20
2021-08-22    20
2021-08-15    20
2021-08-08    20
2021-08-01    20
2021-07-25    20
2021-07-18    20
2021-07-11    20
2021-07-04    20
Name: count, dtype: int64

As per above, Russia has only 2 years of data

### Do most of countries share same dates/weeks?

In [ ]:
# Number of unique weeks per country
df['week'] = pd.to_datetime(df['week'])

print(df.groupby('country_name')['week'].nunique().sort_values(ascending=False))

country_name
Argentina         246
Australia         246
Austria           246
Bahamas           246
Bahrain           246
                 ...
United Kingdom    246
Venezuela         246
Uruguay           246
Vietnam           246
Russia             35
Name: week, Length: 94, dtype: int64

#### It seems most of the countries started at the same time as they share the same amount of weeks!